controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_checkout:
    path: /checkout/{id}/{qty}
    controller: App\Controller\OrderController::checkout
    defaults:
        id: null
        qty: null

app_payment_status:
    path: /payment_status/{status}/{id}/{transactionId}
    controller: App\Controller\PaymentController::paymentStatus
    defaults:
        transactionId: null
